### ISSUE TITLE
Dockerfile should not clone repositories

### ISSUE THREAD

**Issue by Ullaakut** [dapperlabs/dps-rosetta-docker#1]
## Description

In my opinion, making the Dockerfile clone repositories is a mistake, especially when it comes to its own repository.

https://github.com/dapperlabs/dps-rosetta-docker/blob/e5b65478ebdccffb00e21f30e7d5c4f22696111c/Dockerfile#L8-L9

Doing this means that this Dockerfile only runs using the `master` branch of those repositories, and there is no way to specify a commit, or even to use your own local state, without making changes to the Dockerfile.

When developing, most of the time it would make more sense to use the current state of the repo, which can be achieved by running `COPY . /docker` instead for this repository.

### `dps-rosetta-docker`

For this repository, I suggest always using `COPY . /docker` instead of a git clone command. This has multiple advantages: it's instantaneous, works offline and always uses the current state of the repository which is convenient both for development and for deployments.

### `flow-dps`

For other repositories (`flow-dps` in this case) I would suggest making users that want to build this Dockerfile have to copy the `dps` directory in the current working directory instead, so that it can be copied at build time.

This means that they are not forced to use specifically `https://github.com/m4ksio/flow-dps` but can use their own fork, or the upstream remote, but also that they can use their local development branches and are not forced to use `master` at all times, which is essential for development purposes.

## Proposed Diff

```diff
- RUN git clone https://github.com/m4ksio/flow-dps /dps && \
-    git clone https://github.com/dapperlabs/dps-rosetta-docker /docker
+ COPY ./supervisord.conf /docker/supervisord.conf
+ COPY ./run.sh /docker/run.sh
+ COPY ./dps /dps
```

**Comment by m4ksio** [comment]
> ## Description
> In my opinion, making the Dockerfile clone repositories is a mistake, especially when it comes to its own repository.

I totally agree, but that's not that opinion of [Rosetta API dockerization](https://www.rosetta-api.org/docs/node_deployment.html#build-anywhere) which explicitly forbids copying anything from local dir
