### ISSUE TITLE
Where should the Dockerfile be built from?

### ISSUE THREAD

**Issue by Ullaakut** [dapperlabs/dps-rosetta-docker#3]
This is more of a question, because in the following code snippet, I see that we expect the `crypto` package to be in the current working directory. Does this mean that this Dockerfile is supposed to be run from the `flow-go` repository, or that the `crypto` package from the `flow-go` directory should be copied in this one?

https://github.com/dapperlabs/dps-rosetta-docker/blob/e5b65478ebdccffb00e21f30e7d5c4f22696111c/Dockerfile#L24-L34

**Comment by m4ksio** [comment]
As per [Rosetta API](https://www.rosetta-api.org/docs/node_deployment.html#build-anywhere) docker should be able to build from anywhere, ie. not rely on any local files.
