### ISSUE TITLE
Run image is not distroless

### ISSUE THREAD

**Issue by Ullaakut** [dapperlabs/dps-rosetta-docker#4]
## Description

https://github.com/dapperlabs/dps-rosetta-docker/blob/e5b65478ebdccffb00e21f30e7d5c4f22696111c/Dockerfile#L64-L70

The image used for running the actual binary is Ubuntu, which I assume is to be able to run `supervisor`.

If we are to keep using `supervisor` and don't want to go through the hassle of installing it on a `distroless` image, I recommend at least switching to a lighter Docker image, like `alpine`.

Installing `supervisor` on alpine can be done by installing `pip` and then running `pip install supervisor` if I recall correctly.

This should result in a Docker image that is about 4MB instead of about 120MB (not counting the binaries).

**Comment by m4ksio** [comment]
> ## Description
> https://github.com/dapperlabs/dps-rosetta-docker/blob/e5b65478ebdccffb00e21f30e7d5c4f22696111c/Dockerfile#L64-L70
> 
> The image used for running the actual binary is Ubuntu, which I assume is to be able to run `supervisor`.

Yes, but this is also a requirement of [Rosetta API Dockerization](https://www.rosetta-api.org/docs/node_deployment.html#ubuntu-image-compatibility) which explicitly advices against using Alpine.
